### ISSUE TITLE
[PROD] Notifications header

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1785]
## Issue
The Weekly Digest (of operations) and a solo New operation notification has an unacceptable right top part, with missing URL:
![kép](https://github.com/IFRCGo/go-api/assets/6050643/655bf10d-9776-4c7c-80d1-44cae06d8c4b)

Also on Staging.

**Comment by szabozoltan69** [comment]
Could not reproduce locally. It means that some kind of env variable issue exists.

Locally the notification is generated nicely:

![kép](https://github.com/IFRCGo/go-api/assets/6050643/7eafe36c-c60e-4a60-b0aa-1bd095914a45)

**Comment by szabozoltan69** [comment]
These '|quote' transformations are new features in https://github.com/IFRCGo/go-api/blob/terraform/deploy/helm/ifrcgo-helm/templates/config/configmap.yaml#L18-L19 – they may cause new "effects" in notification templates as well.
Do you have any quess how could we use them appropriately in e.g. https://github.com/IFRCGo/go-api/blob/terraform/notifications/templates/design/head1.html#L417 (record.resource_uri) without quotation marks? @batpad @geohacker

**Comment by szabozoltan69** [comment]
https://stackoverflow.com/questions/36954472/removing-quotes-in-a-django-template could help.

**Comment by szabozoltan69** [comment]
With giving FRONTEND_URL issue is solved.

**Comment by tovari** [comment]
Somehow the icon is still missing on all Weekly digest emails:


![Image](https://github.com/IFRCGo/go-api/assets/68283148/9ee26785-bcf4-4390-8103-594d79b3a56e)

**Comment by szabozoltan69** [comment]
Let me check it...
